version: "3"
services:
  ghost:
    image: ghcr.io/tilak999/ghost-on-docker:latest
    restart: always
    ports:
      - 2368:2368
    volumes: [blog-data:/var/lib/ghost/content]
volumes:
  blog-data:
    driver: local
