version: "3"
services:
  ghost:
    image: ghcr.io/tilak999/ghost-on-docker:latest
    restart: always
    environment:
      url: "http://localhost:2368/"
    ports:
      - 2368:2368
    volumes: [blog-data:/var/lib/ghost/content]
volumes:
  blog-data:
    driver: rclone
    driver_opts:
      remote: "oracle-s3:blog-data"
      allow_other: "true"
      vfs_cache_mode: full
      poll_interval: 0
